import { Inter } from "next/font/google";
// import ShopProvider from '../../context/shopContext';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </head>
      <body className={inter.className}>
        {/* <ShopProvider> */}
          {children}
        {/* </ShopProvider> */}
      </body>
    </html>
  );
}
